"""Initial schema: fleet, pairing, telemetry, provider mapping, ledger, settlements.

The table definitions were generated from the SQLAlchemy models and reviewed.
The integrity rules at the end of ``upgrade`` are written by hand: they are the
part of the design that must hold even if application code has a bug.

Revision ID: 0001
Revises:
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_log",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actor_type", sa.String(length=10), nullable=False),
        sa.Column("actor_id", sa.String(length=64), nullable=False),
        sa.Column("action", sa.String(length=80), nullable=False),
        sa.Column("object_type", sa.String(length=40), nullable=False),
        sa.Column("object_id", sa.String(length=64), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=True),
        sa.Column("ip", sa.String(length=64), nullable=False),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("prev_hash", sa.String(length=64), nullable=False),
        sa.Column("hash", sa.String(length=64), nullable=False),
        sa.CheckConstraint(
            "actor_type IN ('user', 'device', 'system')", name="audit_actor"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_log_action"), "audit_log", ["action"], unique=False)
    op.create_index(
        op.f("ix_audit_log_owner_id"), "audit_log", ["owner_id"], unique=False
    )
    op.create_table(
        "owners",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column("legal_name", sa.String(length=200), nullable=False),
        sa.Column("contact_email", sa.String(length=320), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("is_synthetic", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("status IN ('active', 'suspended')", name="owner_status"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "provider_accounts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("provider", sa.String(length=20), nullable=False),
        sa.Column("label", sa.String(length=120), nullable=False),
        sa.Column("external_account_id", sa.String(length=120), nullable=False),
        sa.Column("is_synthetic", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_sync_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_sync_ok", sa.Boolean(), nullable=True),
        sa.Column("last_sync_error", sa.String(length=500), nullable=False),
        sa.CheckConstraint("provider IN ('vast', 'fake')", name="provider_kind"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider", "label", name="uq_provider_label"),
    )
    op.create_table(
        "rate_limit_counters",
        sa.Column("key", sa.String(length=200), nullable=False),
        sa.Column("window_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("key", "window_start"),
    )
    op.create_table(
        "system_info",
        sa.Column("key", sa.String(length=40), nullable=False),
        sa.Column("value", sa.String(length=200), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "ledger_accounts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=120), nullable=False),
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=True),
        sa.Column("provider_account_id", sa.UUID(), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("normal_side", sa.String(length=6), nullable=False),
        sa.Column("allow_overdraft", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "kind IN ('provider_receivable', 'cash_clearing', 'receipts_unallocated', 'unmapped_earnings', 'owner_accrued', 'owner_available', 'owner_reserved', 'owner_in_transit', 'fee_accrued', 'fee_earned')",
            name="account_kind",
        ),
        sa.CheckConstraint("normal_side IN ('debit', 'credit')", name="account_side"),
        sa.ForeignKeyConstraint(["owner_id"], ["owners.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["provider_account_id"], ["provider_accounts.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_index(
        op.f("ix_ledger_accounts_owner_id"),
        "ledger_accounts",
        ["owner_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ledger_accounts_provider_account_id"),
        "ledger_accounts",
        ["provider_account_id"],
        unique=False,
    )
    op.create_table(
        "machines",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("label", sa.String(length=120), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("is_synthetic", sa.Boolean(), nullable=False),
        sa.Column("hardware", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('pending_pairing', 'active', 'retired')", name="machine_status"
        ),
        sa.ForeignKeyConstraint(["owner_id"], ["owners.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_machines_owner_id"), "machines", ["owner_id"], unique=False
    )
    op.create_table(
        "sync_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("provider_account_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_code", sa.String(length=60), nullable=False),
        sa.Column("error", sa.String(length=500), nullable=False),
        sa.Column("stats", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.CheckConstraint(
            "kind IN ('health', 'machines', 'earnings')", name="sync_kind"
        ),
        sa.CheckConstraint("status IN ('ok', 'error', 'blocked')", name="sync_status"),
        sa.ForeignKeyConstraint(
            ["provider_account_id"], ["provider_accounts.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_sync_runs_provider_account_id"),
        "sync_runs",
        ["provider_account_id"],
        unique=False,
    )
    op.create_index(
        "ix_sync_runs_recent",
        "sync_runs",
        ["provider_account_id", "kind", "started_at"],
        unique=False,
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=True),
        sa.Column("password_hash", sa.String(length=500), nullable=True),
        sa.Column("totp_secret_enc", sa.Text(), nullable=True),
        sa.Column("mfa_enabled", sa.Boolean(), nullable=False),
        sa.Column("totp_last_step", sa.BigInteger(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(role = 'owner') = (owner_id IS NOT NULL)", name="user_owner_link"
        ),
        sa.CheckConstraint("role IN ('admin', 'owner', 'auditor')", name="user_role"),
        sa.CheckConstraint("email = lower(email)", name="user_email_lower"),
        sa.ForeignKeyConstraint(["owner_id"], ["owners.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_index(op.f("ix_users_owner_id"), "users", ["owner_id"], unique=False)
    op.create_table(
        "devices",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("machine_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("hostname", sa.String(length=128), nullable=False),
        sa.Column("fingerprint", sa.String(length=80), nullable=False),
        sa.Column("agent_version", sa.String(length=40), nullable=False),
        sa.Column("os_info", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("boot_id", sa.String(length=64), nullable=False),
        sa.Column("last_seq", sa.BigInteger(), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("status IN ('active', 'revoked')", name="device_status"),
        sa.ForeignKeyConstraint(["machine_id"], ["machines.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_devices_machine_id"), "devices", ["machine_id"], unique=True
    )
    op.create_table(
        "earnings_imports",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("provider_account_id", sa.UUID(), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("stats", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("is_synthetic", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('posted', 'duplicate', 'exception', 'held_unverified')",
            name="earnings_import_status",
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["provider_account_id"], ["provider_accounts.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_earnings_imports_content_sha256"),
        "earnings_imports",
        ["content_sha256"],
        unique=False,
    )
    op.create_index(
        op.f("ix_earnings_imports_provider_account_id"),
        "earnings_imports",
        ["provider_account_id"],
        unique=False,
    )
    op.create_table(
        "enrollment_requests",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("machine_id", sa.UUID(), nullable=False),
        sa.Column("locator", sa.String(length=6), nullable=False),
        sa.Column("code_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("failed_attempts", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("device_id", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "status IN ('pending', 'consumed', 'expired', 'locked', 'cancelled')",
            name="enrollment_status",
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["machine_id"], ["machines.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["owner_id"], ["owners.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("locator"),
    )
    op.create_index(
        op.f("ix_enrollment_requests_machine_id"),
        "enrollment_requests",
        ["machine_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_enrollment_requests_owner_id"),
        "enrollment_requests",
        ["owner_id"],
        unique=False,
    )
    op.create_table(
        "exception_items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("dedupe_key", sa.String(length=200), nullable=True),
        sa.Column("summary", sa.String(length=500), nullable=False),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("provider_account_id", sa.UUID(), nullable=True),
        sa.Column("owner_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_by", sa.UUID(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolution", sa.String(length=1000), nullable=False),
        sa.CheckConstraint(
            "kind IN ('unmapped_machine', 'total_mismatch', 'unknown_currency', 'unexplained_adjustment', 'no_fee_schedule', 'unverified_semantics', 'receipt_remainder', 'over_received', 'malformed_report', 'missing_from_report')",
            name="exception_kind",
        ),
        sa.CheckConstraint("status IN ('open', 'resolved')", name="exception_status"),
        sa.ForeignKeyConstraint(["owner_id"], ["owners.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["provider_account_id"], ["provider_accounts.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["resolved_by"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dedupe_key"),
    )
    op.create_index(
        op.f("ix_exception_items_owner_id"),
        "exception_items",
        ["owner_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_exception_items_provider_account_id"),
        "exception_items",
        ["provider_account_id"],
        unique=False,
    )
    op.create_table(
        "fee_schedules",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=True),
        sa.Column("rate", sa.Numeric(precision=9, scale=8), nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("note", sa.String(length=500), nullable=False),
        sa.Column("is_demo_assumption", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("rate >= 0 AND rate < 1", name="fee_rate_range"),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["owner_id"], ["owners.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_fee_schedules_owner_id"), "fee_schedules", ["owner_id"], unique=False
    )
    op.create_index(
        "uq_fee_owner_effective",
        "fee_schedules",
        ["owner_id", "effective_from"],
        unique=True,
        postgresql_nulls_not_distinct=True,
    )
    op.create_table(
        "journal_entries",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("entry_type", sa.String(length=40), nullable=False),
        sa.Column("idempotency_key", sa.String(length=200), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("occurred_on", sa.Date(), nullable=False),
        sa.Column("posted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("reverses_entry_id", sa.UUID(), nullable=True),
        sa.Column("ref_type", sa.String(length=40), nullable=False),
        sa.Column("ref_id", sa.String(length=64), nullable=False),
        sa.Column(
            "created_txid",
            sa.BigInteger(),
            server_default=sa.text("txid_current()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["reverses_entry_id"], ["journal_entries.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    op.create_index(
        op.f("ix_journal_entries_reverses_entry_id"),
        "journal_entries",
        ["reverses_entry_id"],
        unique=True,
    )
    op.create_index(
        "ix_journal_ref", "journal_entries", ["ref_type", "ref_id"], unique=False
    )
    op.create_table(
        "ledger_balances",
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("balance", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"], ["ledger_accounts.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("account_id"),
    )
    op.create_table(
        "machine_ownership",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("machine_id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column("changed_by", sa.UUID(), nullable=True),
        sa.Column("reason", sa.String(length=500), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "valid_to IS NULL OR valid_to > valid_from", name="ownership_range"
        ),
        sa.ForeignKeyConstraint(["changed_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["machine_id"], ["machines.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["owner_id"], ["owners.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_machine_ownership_machine_id"),
        "machine_ownership",
        ["machine_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_machine_ownership_owner_id"),
        "machine_ownership",
        ["owner_id"],
        unique=False,
    )
    op.create_index(
        "uq_machine_current_owner",
        "machine_ownership",
        ["machine_id"],
        unique=True,
        postgresql_where=sa.text("valid_to IS NULL"),
    )
    op.create_table(
        "owner_beneficiaries",
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("details_enc", sa.Text(), nullable=False),
        sa.Column("masked_hint", sa.String(length=80), nullable=False),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["owner_id"], ["owners.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["updated_by"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("owner_id"),
    )
    op.create_table(
        "payout_batches",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("idempotency_key", sa.String(length=120), nullable=False),
        sa.Column("note", sa.String(length=500), nullable=False),
        sa.Column("is_synthetic", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("approved_by", sa.UUID(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("export_sha256", sa.String(length=64), nullable=False),
        sa.Column("export_count", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "status IN ('draft', 'approved', 'submitted', 'closed', 'cancelled')",
            name="batch_status",
        ),
        sa.ForeignKeyConstraint(["approved_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    op.create_table(
        "provider_machines",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("provider_account_id", sa.UUID(), nullable=False),
        sa.Column("external_id", sa.String(length=64), nullable=False),
        sa.Column("machine_id", sa.UUID(), nullable=True),
        sa.Column("bound_from", sa.Date(), nullable=True),
        sa.Column("bound_by", sa.UUID(), nullable=True),
        sa.Column("bound_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("hostname", sa.String(length=200), nullable=False),
        sa.Column("gpu_name", sa.String(length=200), nullable=False),
        sa.Column("num_gpus", sa.Integer(), nullable=True),
        sa.Column("snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("rental_state", sa.String(length=24), nullable=False),
        sa.Column("listed", sa.Boolean(), nullable=True),
        sa.Column("state_detail", sa.String(length=500), nullable=False),
        sa.Column("state_observed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("missing_since", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "rental_state IN ('unknown', 'idle', 'active_contracts', 'stopped_instances', 'stored_data')",
            name="provider_rental_state",
        ),
        sa.CheckConstraint(
            "(machine_id IS NULL) = (bound_from IS NULL)",
            name="provider_binding_complete",
        ),
        sa.ForeignKeyConstraint(["bound_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["machine_id"], ["machines.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["provider_account_id"], ["provider_accounts.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "provider_account_id", "external_id", name="uq_provider_machine"
        ),
    )
    op.create_index(
        op.f("ix_provider_machines_machine_id"),
        "provider_machines",
        ["machine_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_provider_machines_provider_account_id"),
        "provider_machines",
        ["provider_account_id"],
        unique=False,
    )
    op.create_table(
        "source_snapshots",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("provider_account_id", sa.UUID(), nullable=True),
        sa.Column("kind", sa.String(length=40), nullable=False),
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("body", sa.LargeBinary(), nullable=False),
        sa.Column("is_synthetic", sa.Boolean(), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["provider_account_id"], ["provider_accounts.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_source_snapshots_provider_account_id"),
        "source_snapshots",
        ["provider_account_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_source_snapshots_sha256"), "source_snapshots", ["sha256"], unique=False
    )
    op.create_table(
        "user_sessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("csrf_token", sa.String(length=64), nullable=False),
        sa.Column("mfa_verified", sa.Boolean(), nullable=False),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ip", sa.String(length=64), nullable=False),
        sa.Column("user_agent", sa.String(length=300), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_index(
        op.f("ix_user_sessions_user_id"), "user_sessions", ["user_id"], unique=False
    )
    op.create_table(
        "device_credentials",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("device_id", sa.UUID(), nullable=False),
        sa.Column("secret_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("first_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("superseded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('active', 'superseded', 'revoked')", name="credential_status"
        ),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_device_credentials_device_id"),
        "device_credentials",
        ["device_id"],
        unique=False,
    )
    op.create_table(
        "earning_buckets",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("provider_account_id", sa.UUID(), nullable=False),
        sa.Column("external_machine_id", sa.String(length=64), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("machine_id", sa.UUID(), nullable=True),
        sa.Column("owner_id", sa.UUID(), nullable=True),
        sa.Column("fee_schedule_id", sa.UUID(), nullable=True),
        sa.Column("fee_rate", sa.Numeric(precision=9, scale=8), nullable=True),
        sa.Column("reported_amount", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("received_amount", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("owner_accrued", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("fee_accrued", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("owner_released", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("fee_released", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("revision_count", sa.Integer(), nullable=False),
        sa.Column("is_synthetic", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(status = 'mapped') = (owner_id IS NOT NULL AND machine_id IS NOT NULL AND fee_schedule_id IS NOT NULL AND fee_rate IS NOT NULL)",
            name="bucket_mapping_complete",
        ),
        sa.CheckConstraint("status IN ('mapped', 'unmapped')", name="bucket_status"),
        sa.ForeignKeyConstraint(
            ["fee_schedule_id"], ["fee_schedules.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["machine_id"], ["machines.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["owner_id"], ["owners.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["provider_account_id"], ["provider_accounts.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "provider_account_id",
            "external_machine_id",
            "day",
            name="uq_earning_bucket",
        ),
    )
    op.create_index(
        "ix_bucket_owner_day", "earning_buckets", ["owner_id", "day"], unique=False
    )
    op.create_index(
        op.f("ix_earning_buckets_machine_id"),
        "earning_buckets",
        ["machine_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_earning_buckets_owner_id"),
        "earning_buckets",
        ["owner_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_earning_buckets_provider_account_id"),
        "earning_buckets",
        ["provider_account_id"],
        unique=False,
    )
    op.create_table(
        "journal_lines",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("entry_id", sa.UUID(), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.CheckConstraint("amount <> 0", name="journal_line_nonzero"),
        sa.ForeignKeyConstraint(
            ["account_id"], ["ledger_accounts.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["entry_id"], ["journal_entries.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_journal_lines_account_id"),
        "journal_lines",
        ["account_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_journal_lines_entry_id"), "journal_lines", ["entry_id"], unique=False
    )
    op.create_table(
        "operations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("machine_id", sa.UUID(), nullable=False),
        sa.Column("device_id", sa.UUID(), nullable=False),
        sa.Column("type", sa.String(length=40), nullable=False),
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("nonce", sa.String(length=64), nullable=False),
        sa.Column("requested_by", sa.UUID(), nullable=True),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("detail", sa.String(length=2000), nullable=False),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("safety", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.CheckConstraint(
            "status IN ('pending', 'delivered', 'accepted', 'succeeded', 'failed', 'rejected', 'expired', 'cancelled', 'blocked')",
            name="operation_status",
        ),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["machine_id"], ["machines.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["requested_by"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_operations_device_id"), "operations", ["device_id"], unique=False
    )
    op.create_index(
        op.f("ix_operations_machine_id"), "operations", ["machine_id"], unique=False
    )
    op.create_table(
        "payout_items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("batch_id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("beneficiary_snapshot_enc", sa.Text(), nullable=False),
        sa.Column("external_reference", sa.String(length=120), nullable=False),
        sa.Column("failure_reason", sa.String(length=500), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('draft', 'reserved', 'submitted', 'uncertain', 'confirmed_paid', 'failed', 'reversed', 'cancelled')",
            name="payout_item_status",
        ),
        sa.CheckConstraint("amount > 0", name="payout_item_positive"),
        sa.ForeignKeyConstraint(
            ["batch_id"], ["payout_batches.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["owner_id"], ["owners.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("batch_id", "owner_id", name="uq_payout_item_owner"),
    )
    op.create_index(
        op.f("ix_payout_items_batch_id"), "payout_items", ["batch_id"], unique=False
    )
    op.create_index(
        op.f("ix_payout_items_owner_id"), "payout_items", ["owner_id"], unique=False
    )
    op.create_table(
        "provider_binding_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("provider_machine_id", sa.UUID(), nullable=False),
        sa.Column("machine_id", sa.UUID(), nullable=False),
        sa.Column("action", sa.String(length=10), nullable=False),
        sa.Column("effective_day", sa.Date(), nullable=False),
        sa.Column("by_user", sa.UUID(), nullable=True),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.CheckConstraint("action IN ('bind', 'unbind')", name="binding_action"),
        sa.ForeignKeyConstraint(["by_user"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["machine_id"], ["machines.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["provider_machine_id"], ["provider_machines.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_provider_binding_events_machine_id"),
        "provider_binding_events",
        ["machine_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_provider_binding_events_provider_machine_id"),
        "provider_binding_events",
        ["provider_machine_id"],
        unique=False,
    )
    op.create_table(
        "provider_receipts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("provider_account_id", sa.UUID(), nullable=False),
        sa.Column("reference", sa.String(length=120), nullable=False),
        sa.Column("received_on", sa.Date(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column(
            "allocated_amount", sa.Numeric(precision=24, scale=8), nullable=False
        ),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("evidence_source", sa.String(length=30), nullable=False),
        sa.Column("evidence_note", sa.String(length=1000), nullable=False),
        sa.Column("is_synthetic", sa.Boolean(), nullable=False),
        sa.Column("journal_entry_id", sa.UUID(), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("voided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("voided_by", sa.UUID(), nullable=True),
        sa.Column("void_reason", sa.String(length=500), nullable=False),
        sa.CheckConstraint(
            "evidence_source IN ('bank_statement', 'payout_provider_statement')",
            name="receipt_evidence_source",
        ),
        sa.CheckConstraint(
            "allocated_amount >= 0 AND allocated_amount <= amount",
            name="receipt_allocation_bound",
        ),
        sa.CheckConstraint("amount > 0", name="receipt_positive"),
        sa.CheckConstraint(
            "voided_at IS NULL OR allocated_amount = 0", name="receipt_void_unallocated"
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["journal_entry_id"], ["journal_entries.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["provider_account_id"], ["provider_accounts.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["voided_by"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_provider_receipts_provider_account_id"),
        "provider_receipts",
        ["provider_account_id"],
        unique=False,
    )
    op.create_index(
        "uq_receipt_reference",
        "provider_receipts",
        ["provider_account_id", "reference"],
        unique=True,
        postgresql_where=sa.text("voided_at IS NULL"),
    )
    op.create_table(
        "telemetry_samples",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.UUID(), nullable=False),
        sa.Column("machine_id", sa.UUID(), nullable=False),
        sa.Column("seq", sa.BigInteger(), nullable=False),
        sa.Column("boot_id", sa.String(length=64), nullable=False),
        sa.Column("collected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("synthetic", sa.Boolean(), nullable=False),
        sa.Column("gpu_count", sa.Integer(), nullable=False),
        sa.Column("gpu_util_avg", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("gpu_power_w", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("gpu_temp_max", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["machine_id"], ["machines.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_id", "seq", name="uq_telemetry_device_seq"),
    )
    op.create_index(
        "ix_telemetry_machine_time",
        "telemetry_samples",
        ["machine_id", "collected_at"],
        unique=False,
    )
    op.create_table(
        "earning_revisions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("bucket_id", sa.UUID(), nullable=False),
        sa.Column("import_id", sa.UUID(), nullable=False),
        sa.Column("revision_no", sa.Integer(), nullable=False),
        sa.Column("reported_amount", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("delta", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column(
            "components", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("journal_entry_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["bucket_id"], ["earning_buckets.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["import_id"], ["earnings_imports.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["journal_entry_id"], ["journal_entries.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("bucket_id", "revision_no", name="uq_bucket_revision"),
    )
    op.create_index(
        op.f("ix_earning_revisions_bucket_id"),
        "earning_revisions",
        ["bucket_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_earning_revisions_import_id"),
        "earning_revisions",
        ["import_id"],
        unique=False,
    )
    op.create_table(
        "payout_evidence",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("item_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=24), nullable=False),
        sa.Column("reference", sa.String(length=200), nullable=False),
        sa.Column("note", sa.String(length=1000), nullable=False),
        sa.Column("recorded_by", sa.UUID(), nullable=True),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "kind IN ('submission', 'bank_confirmation', 'bank_rejection', 'bank_return', 'uncertain_outcome')",
            name="payout_evidence_kind",
        ),
        sa.ForeignKeyConstraint(["item_id"], ["payout_items.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["recorded_by"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_payout_evidence_item_id"), "payout_evidence", ["item_id"], unique=False
    )
    op.create_index(
        "uq_bank_confirmation_reference",
        "payout_evidence",
        ["reference"],
        unique=True,
        postgresql_where=sa.text("kind = 'bank_confirmation'"),
    )
    op.create_table(
        "receipt_allocations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("receipt_id", sa.UUID(), nullable=False),
        sa.Column("bucket_id", sa.UUID(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("owner_released", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("fee_released", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("journal_entry_id", sa.UUID(), nullable=False),
        sa.Column("request_key", sa.String(length=120), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("amount <> 0", name="allocation_nonzero"),
        sa.ForeignKeyConstraint(
            ["bucket_id"], ["earning_buckets.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["journal_entry_id"], ["journal_entries.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["receipt_id"], ["provider_receipts.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_receipt_allocations_bucket_id"),
        "receipt_allocations",
        ["bucket_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_receipt_allocations_receipt_id"),
        "receipt_allocations",
        ["receipt_id"],
        unique=False,
    )
    op.create_index(
        "uq_allocation_request",
        "receipt_allocations",
        ["receipt_id", "bucket_id", "request_key"],
        unique=True,
        postgresql_where=sa.text("request_key <> ''"),
    )
    # ### end Alembic commands ###

    # ------------------------------------------------------------------
    # Hand-written integrity rules
    # ------------------------------------------------------------------

    # Ownership periods of one machine may never overlap.
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")
    op.execute(
        """
        ALTER TABLE machine_ownership ADD CONSTRAINT machine_ownership_no_overlap
        EXCLUDE USING gist (machine_id WITH =, daterange(valid_from, valid_to, '[)') WITH &&)
        """
    )

    # Append-only tables: the journal and the audit trail.
    op.execute(
        """
        CREATE FUNCTION hm_forbid_change() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            RAISE EXCEPTION '% on % is not allowed: this table is append-only', TG_OP, TG_TABLE_NAME
                USING ERRCODE = 'restrict_violation';
        END $$
        """
    )
    # ledger_accounts is included: changing an account's side or its overdraft
    # flag after the fact would silently change what the journal means.
    for table in ("journal_entries", "journal_lines", "audit_log", "ledger_accounts"):
        op.execute(
            f"CREATE TRIGGER {table}_append_only BEFORE UPDATE OR DELETE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION hm_forbid_change()"
        )
        op.execute(
            f"CREATE TRIGGER {table}_no_truncate BEFORE TRUNCATE ON {table} "
            "FOR EACH STATEMENT EXECUTE FUNCTION hm_forbid_change()"
        )

    # A committed entry can never grow: lines are accepted only from the
    # transaction that created the entry. Without this, two extra lines that
    # cancel out could move money inside an old entry and still "balance".
    op.execute(
        """
        CREATE FUNCTION hm_stamp_entry_txid() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            NEW.created_txid := txid_current();
            RETURN NEW;
        END $$
        """
    )
    op.execute(
        "CREATE TRIGGER journal_entries_stamp BEFORE INSERT ON journal_entries "
        "FOR EACH ROW EXECUTE FUNCTION hm_stamp_entry_txid()"
    )
    op.execute(
        """
        CREATE FUNCTION hm_lines_same_transaction() RETURNS trigger LANGUAGE plpgsql AS $$
        DECLARE
            entry_txid bigint;
        BEGIN
            SELECT created_txid INTO entry_txid FROM journal_entries WHERE id = NEW.entry_id;
            IF entry_txid IS DISTINCT FROM txid_current() THEN
                RAISE EXCEPTION 'journal entry % is closed: lines can only be added by the transaction that created it',
                    NEW.entry_id USING ERRCODE = 'restrict_violation';
            END IF;
            RETURN NEW;
        END $$
        """
    )
    op.execute(
        "CREATE TRIGGER journal_lines_same_transaction BEFORE INSERT ON journal_lines "
        "FOR EACH ROW EXECUTE FUNCTION hm_lines_same_transaction()"
    )

    # Running balances, and refusal of overdrafts on protected accounts. The
    # function is SECURITY DEFINER so that the runtime database role needs no
    # write privilege on ledger_balances at all (see docs/operations.md). The
    # UPDATE takes a row lock on the balance, so concurrent transactions that
    # touch the same account are serialised by the database itself.
    op.execute(
        """
        CREATE FUNCTION hm_apply_journal_line() RETURNS trigger LANGUAGE plpgsql
        SECURITY DEFINER SET search_path = public, pg_temp AS $$
        DECLARE
            new_balance numeric(24, 8);
            side text;
            overdraft boolean;
        BEGIN
            INSERT INTO ledger_balances (account_id, balance, updated_at)
            VALUES (NEW.account_id, NEW.amount, now())
            ON CONFLICT (account_id) DO UPDATE
                SET balance = ledger_balances.balance + EXCLUDED.balance, updated_at = now()
            RETURNING balance INTO new_balance;

            SELECT normal_side, allow_overdraft INTO side, overdraft
            FROM ledger_accounts WHERE id = NEW.account_id;

            IF NOT overdraft AND (
                (side = 'debit' AND new_balance < 0) OR (side = 'credit' AND new_balance > 0)
            ) THEN
                RAISE EXCEPTION 'ledger overdraft on account %', NEW.account_id
                    USING ERRCODE = 'check_violation';
            END IF;
            RETURN NEW;
        END $$
        """
    )
    op.execute(
        "CREATE TRIGGER journal_lines_apply AFTER INSERT ON journal_lines "
        "FOR EACH ROW EXECUTE FUNCTION hm_apply_journal_line()"
    )

    # Every entry balances to zero per currency and has at least two lines.
    # Checked at commit, once all lines of the entry are in.
    op.execute(
        """
        CREATE FUNCTION hm_check_entry_balanced() RETURNS trigger LANGUAGE plpgsql AS $$
        DECLARE
            bad record;
            line_count integer;
        BEGIN
            SELECT count(*) INTO line_count FROM journal_lines WHERE entry_id = NEW.entry_id;
            IF line_count < 2 THEN
                RAISE EXCEPTION 'journal entry % has fewer than two lines', NEW.entry_id
                    USING ERRCODE = 'check_violation';
            END IF;
            FOR bad IN
                SELECT currency, sum(amount) AS total FROM journal_lines
                WHERE entry_id = NEW.entry_id GROUP BY currency HAVING sum(amount) <> 0
            LOOP
                RAISE EXCEPTION 'journal entry % does not balance in %: %', NEW.entry_id, bad.currency, bad.total
                    USING ERRCODE = 'check_violation';
            END LOOP;
            RETURN NULL;
        END $$
        """
    )
    op.execute(
        "CREATE CONSTRAINT TRIGGER journal_lines_balanced AFTER INSERT ON journal_lines "
        "DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION hm_check_entry_balanced()"
    )

    # An entry without any line is also refused at commit.
    op.execute(
        """
        CREATE FUNCTION hm_check_entry_has_lines() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM journal_lines WHERE entry_id = NEW.id) THEN
                RAISE EXCEPTION 'journal entry % has no lines', NEW.id USING ERRCODE = 'check_violation';
            END IF;
            RETURN NULL;
        END $$
        """
    )
    op.execute(
        "CREATE CONSTRAINT TRIGGER journal_entries_have_lines AFTER INSERT ON journal_entries "
        "DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION hm_check_entry_has_lines()"
    )

    # The balance cache is written by the trigger only.
    op.execute(
        """
        CREATE FUNCTION hm_guard_balance_write() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            IF pg_trigger_depth() < 2 THEN
                RAISE EXCEPTION 'ledger_balances is maintained by the journal trigger only'
                    USING ERRCODE = 'restrict_violation';
            END IF;
            RETURN COALESCE(NEW, OLD);
        END $$
        """
    )
    op.execute(
        "CREATE TRIGGER ledger_balances_guard BEFORE INSERT OR UPDATE OR DELETE ON ledger_balances "
        "FOR EACH ROW EXECUTE FUNCTION hm_guard_balance_write()"
    )
    op.execute(
        "CREATE TRIGGER ledger_balances_no_truncate BEFORE TRUNCATE ON ledger_balances "
        "FOR EACH STATEMENT EXECUTE FUNCTION hm_forbid_change()"
    )


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS ledger_balances_guard ON ledger_balances")
    op.execute("DROP TRIGGER IF EXISTS journal_entries_have_lines ON journal_entries")
    op.execute("DROP TRIGGER IF EXISTS journal_lines_balanced ON journal_lines")
    op.execute("DROP TRIGGER IF EXISTS journal_lines_apply ON journal_lines")
    op.execute("DROP TRIGGER IF EXISTS ledger_balances_no_truncate ON ledger_balances")
    op.execute("DROP TRIGGER IF EXISTS journal_lines_same_transaction ON journal_lines")
    op.execute("DROP TRIGGER IF EXISTS journal_entries_stamp ON journal_entries")
    for table in ("journal_entries", "journal_lines", "audit_log", "ledger_accounts"):
        op.execute(f"DROP TRIGGER IF EXISTS {table}_append_only ON {table}")
        op.execute(f"DROP TRIGGER IF EXISTS {table}_no_truncate ON {table}")
    for function in (
        "hm_guard_balance_write",
        "hm_lines_same_transaction",
        "hm_stamp_entry_txid",
        "hm_check_entry_has_lines",
        "hm_check_entry_balanced",
        "hm_apply_journal_line",
        "hm_forbid_change",
    ):
        op.execute(f"DROP FUNCTION IF EXISTS {function}()")
    op.execute(
        "ALTER TABLE machine_ownership DROP CONSTRAINT IF EXISTS machine_ownership_no_overlap"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_allocation_request",
        table_name="receipt_allocations",
        postgresql_where=sa.text("request_key <> ''"),
    )
    op.drop_index(
        op.f("ix_receipt_allocations_receipt_id"), table_name="receipt_allocations"
    )
    op.drop_index(
        op.f("ix_receipt_allocations_bucket_id"), table_name="receipt_allocations"
    )
    op.drop_table("receipt_allocations")
    op.drop_index(
        "uq_bank_confirmation_reference",
        table_name="payout_evidence",
        postgresql_where=sa.text("kind = 'bank_confirmation'"),
    )
    op.drop_index(op.f("ix_payout_evidence_item_id"), table_name="payout_evidence")
    op.drop_table("payout_evidence")
    op.drop_index(
        op.f("ix_earning_revisions_import_id"), table_name="earning_revisions"
    )
    op.drop_index(
        op.f("ix_earning_revisions_bucket_id"), table_name="earning_revisions"
    )
    op.drop_table("earning_revisions")
    op.drop_index("ix_telemetry_machine_time", table_name="telemetry_samples")
    op.drop_table("telemetry_samples")
    op.drop_index(
        "uq_receipt_reference",
        table_name="provider_receipts",
        postgresql_where=sa.text("voided_at IS NULL"),
    )
    op.drop_index(
        op.f("ix_provider_receipts_provider_account_id"), table_name="provider_receipts"
    )
    op.drop_table("provider_receipts")
    op.drop_index(
        op.f("ix_provider_binding_events_provider_machine_id"),
        table_name="provider_binding_events",
    )
    op.drop_index(
        op.f("ix_provider_binding_events_machine_id"),
        table_name="provider_binding_events",
    )
    op.drop_table("provider_binding_events")
    op.drop_index(op.f("ix_payout_items_owner_id"), table_name="payout_items")
    op.drop_index(op.f("ix_payout_items_batch_id"), table_name="payout_items")
    op.drop_table("payout_items")
    op.drop_index(op.f("ix_operations_machine_id"), table_name="operations")
    op.drop_index(op.f("ix_operations_device_id"), table_name="operations")
    op.drop_table("operations")
    op.drop_index(op.f("ix_journal_lines_entry_id"), table_name="journal_lines")
    op.drop_index(op.f("ix_journal_lines_account_id"), table_name="journal_lines")
    op.drop_table("journal_lines")
    op.drop_index(
        op.f("ix_earning_buckets_provider_account_id"), table_name="earning_buckets"
    )
    op.drop_index(op.f("ix_earning_buckets_owner_id"), table_name="earning_buckets")
    op.drop_index(op.f("ix_earning_buckets_machine_id"), table_name="earning_buckets")
    op.drop_index("ix_bucket_owner_day", table_name="earning_buckets")
    op.drop_table("earning_buckets")
    op.drop_index(
        op.f("ix_device_credentials_device_id"), table_name="device_credentials"
    )
    op.drop_table("device_credentials")
    op.drop_index(op.f("ix_user_sessions_user_id"), table_name="user_sessions")
    op.drop_table("user_sessions")
    op.drop_index(op.f("ix_source_snapshots_sha256"), table_name="source_snapshots")
    op.drop_index(
        op.f("ix_source_snapshots_provider_account_id"), table_name="source_snapshots"
    )
    op.drop_table("source_snapshots")
    op.drop_index(
        op.f("ix_provider_machines_provider_account_id"), table_name="provider_machines"
    )
    op.drop_index(
        op.f("ix_provider_machines_machine_id"), table_name="provider_machines"
    )
    op.drop_table("provider_machines")
    op.drop_table("payout_batches")
    op.drop_table("owner_beneficiaries")
    op.drop_index(
        "uq_machine_current_owner",
        table_name="machine_ownership",
        postgresql_where=sa.text("valid_to IS NULL"),
    )
    op.drop_index(op.f("ix_machine_ownership_owner_id"), table_name="machine_ownership")
    op.drop_index(
        op.f("ix_machine_ownership_machine_id"), table_name="machine_ownership"
    )
    op.drop_table("machine_ownership")
    op.drop_table("ledger_balances")
    op.drop_index("ix_journal_ref", table_name="journal_entries")
    op.drop_index(
        op.f("ix_journal_entries_reverses_entry_id"), table_name="journal_entries"
    )
    op.drop_table("journal_entries")
    op.drop_index(
        "uq_fee_owner_effective",
        table_name="fee_schedules",
        postgresql_nulls_not_distinct=True,
    )
    op.drop_index(op.f("ix_fee_schedules_owner_id"), table_name="fee_schedules")
    op.drop_table("fee_schedules")
    op.drop_index(
        op.f("ix_exception_items_provider_account_id"), table_name="exception_items"
    )
    op.drop_index(op.f("ix_exception_items_owner_id"), table_name="exception_items")
    op.drop_table("exception_items")
    op.drop_index(
        op.f("ix_enrollment_requests_owner_id"), table_name="enrollment_requests"
    )
    op.drop_index(
        op.f("ix_enrollment_requests_machine_id"), table_name="enrollment_requests"
    )
    op.drop_table("enrollment_requests")
    op.drop_index(
        op.f("ix_earnings_imports_provider_account_id"), table_name="earnings_imports"
    )
    op.drop_index(
        op.f("ix_earnings_imports_content_sha256"), table_name="earnings_imports"
    )
    op.drop_table("earnings_imports")
    op.drop_index(op.f("ix_devices_machine_id"), table_name="devices")
    op.drop_table("devices")
    op.drop_index(op.f("ix_users_owner_id"), table_name="users")
    op.drop_table("users")
    op.drop_index("ix_sync_runs_recent", table_name="sync_runs")
    op.drop_index(op.f("ix_sync_runs_provider_account_id"), table_name="sync_runs")
    op.drop_table("sync_runs")
    op.drop_index(op.f("ix_machines_owner_id"), table_name="machines")
    op.drop_table("machines")
    op.drop_index(
        op.f("ix_ledger_accounts_provider_account_id"), table_name="ledger_accounts"
    )
    op.drop_index(op.f("ix_ledger_accounts_owner_id"), table_name="ledger_accounts")
    op.drop_table("ledger_accounts")
    op.drop_table("system_info")
    op.drop_table("rate_limit_counters")
    op.drop_table("provider_accounts")
    op.drop_table("owners")
    op.drop_index(op.f("ix_audit_log_owner_id"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_action"), table_name="audit_log")
    op.drop_table("audit_log")
    # ### end Alembic commands ###
